### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by DregondRahl** [maoosi/prisma-appsync#21]
Right now, displaying and handling errors can be a bit confusing. I'm not sure if there is a best practice for this case but even with a unique constraint failure it can throw a lot of text. 

![recording](https://user-images.githubusercontent.com/749080/123665700-25544980-d856-11eb-811f-23fb84e473c8.gif)

**Comment by maoosi** [comment]
The current Lambda Function provided is supposed to treat errors in two ways:
* What is returned to the Client doing the API call is intended to be a “public-facing” error (generic message, stripped out from details that could lead to security issues).
* On the other end, the “developer-facing“ error (what you are seeing in the AppSync console) is displaying full details for logging in CloudWatch.
 
But you are right in saying that the developer-facing one could probably be improved. I never really looked into it, but there are few Prisma guides dedicated to error handling:
 
https://www.prisma.io/docs/reference/api-reference/error-reference/
https://www.prisma.io/docs/concepts/components/prisma-client/handling-exceptions-and-errors
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#error-formats
 
 I’ll add this issue to the roadmap so that we can properly look into it.
