### ISSUE TITLE
Prisma CDK lambda layer construct 

### ISSUE THREAD

**Issue by revmischa** [maoosi/prisma-appsync#27]
Hi, love this project! I created a reusable CDK construct to generate a prisma layer, including support for prisma-appsync and bundling the prisma directory automatically. Love to get your feedback and maybe a note in the docs if it looks good.

PR is open here: https://github.com/jetbridge/jetkit-cdk/pull/30

**Comment by maoosi** [comment]
Hey @revmischa, thanks for your contribution!

From Jetkit docs, I understand that the PrismaLayer Class is creating the Lambda function with the right config, but I couldn’t find anything around AWS AppSync. Would you have a code example to share?

**Comment by revmischa** [comment]
Oh it basically is just [aware enough](https://github.com/jetbridge/jetkit-cdk/blob/master/src/cdk/lambda/prismaLayer.ts#L165) to copy over the prisma-appsync module. Didn't mean more than that for now. Currently trying out prisma-appsync for our project and would be happy to package up a bit of the boilerplate as a reusable CDK construct at some point.

**Comment by maoosi** [comment]
Okay, got it! Sadly this will not be enough to make it compatible with Prisma-AppSync.

For full support, it would require a new AppSync Construct (using Direct Lambda Resolvers) and the ability to combine the AppSyncLayer with the PrismaLayer.

An extra requirement would be the ability to add extra files into the PrismaLayer and to add custom mapping in the AppSyncLayer - so that it is also compatible with that part of the package: [prisma-appsync.vercel.app/guides/extending-api](https://prisma-appsync.vercel.app/guides/extending-api.html).

I do like the simplicity of the Jetkit API though, so I am very curious to see how it evolve (especially around AppSync).

**Comment by revmischa** [comment]
> An extra requirement would be the ability to add extra files into the PrismaLayer and to add custom mapping in the AppSyncLayer - so that it is also compatible with that part of the package: [prisma-appsync.vercel.app/guides/extending-api](https://prisma-appsync.vercel.app/guides/extending-api.html).

Sure, right now it simply copies the entire prisma directory to the layer and that appears to be sufficient.

> I do like the simplicity of the Jetkit API though, so I am very curious to see how it evolve (especially around AppSync).

I could imagine adding decorators like `@Resolver({ type: MUTATION....`
