### ISSUE TITLE
Embedded Document support for mongodb + prisma 3.10.0

### ISSUE THREAD

**Issue by mikerudge** [maoosi/prisma-appsync#37]
Prisma has just released 3.10.0 which has support for mongodb embedded docs. 

```
model Product {
  id     String  @id @default(auto()) @map("_id") @db.ObjectId
  name   String
  photos Photo[]
}

type Photo {
  height Int
  width  Int
  url    String
}
```

However at the moment `prisma-appsync` throws an error(s)
 
```
Error: Unknown type "Photo".

Unknown type "Photo".

Unknown type "Photo".

Unknown type "Photo".
    at assertValidSDL (.../node_modules/prisma-appsync/dist/generator.js:239891:15)
```

Know this has only just come out, but wanted to raise it so its on your radar! 👍

**Comment by ryparker** [comment]
Noticing this with postgres database as well.

**Comment by ryparker** [comment]
The error seems to be throwing when [prettier is attempting to parse the generated graphql schema](https://github.com/maoosi/prisma-appsync/blob/feae1a466490c610a1f2d58a9cfb85971114ac13/src/generator/compiler.ts#L111-L118).

It looks like the prettier error is caused by the Graphql schema's input field values not being camel case.

Here's an example error:

```sh
Unknown type "github_issue_labels_v3CreateInput". Did you mean "GithubIssueLabelsV3CreateInput", "GithubIssueLabelsV3UpdateInput", "GithubIssueLabelsV3CreateManyInput", "GithubIssueLabelsV3OrderByInput", or "GithubIssueLabelsV3UpsertInput"?
```

Here's the graphql schema Input that failed the parser
```graphql
input GithubIssuesV3GithubIssueLabelsV3CreateRelationsInput {
    create: [github_issue_labels_v3CreateInput]
    connect: [github_issue_labels_v3WhereUniqueInput]
    connectOrCreate: [github_issue_labels_v3ConnectOrCreateInput]
}
```

However there is no `github_issue_labels_v3CreateInput` in the schema but there is a `GithubIssueLabelsV3CreateInput` which I believe is the correct value it should be using.

```graphql
input GithubIssueLabelsV3CreateInput {
    issue_id: Int!
    repo_id: Int!
    label: String!
    github_issues_v3: GithubIssueLabelsV3GithubIssuesV3CreateRelationsInput!
    github_repo_v3: GithubIssueLabelsV3GithubRepoV3CreateRelationsInput!
}
```

[Here is where the problem `input`'s seem to be generated from.](https://github.com/maoosi/prisma-appsync/blob/feae1a466490c610a1f2d58a9cfb85971114ac13/src/generator/templates/schema.gql.njk#L158-L195)

**Comment by ryparker** [comment]
Fix here: https://github.com/maoosi/prisma-appsync/pull/38
